name: Run Git contributions merger daily

on:
  schedule:
    # Run at 17:00 UTC / 18:00 CET every day
    - cron: '42 14 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r gitContrib/requirements.txt # for dependencies

    - name: Run Python script
      env:
        GITCONTRIB_GITHUB_API_URL: ${{ secrets.GITCONTRIB_GITHUB_API_URL }}
        GITCONTRIB_GITLAB_API_URL: ${{ secrets.GITCONTRIB_GITLAB_API_URL }}
        GITCONTRIB_GITLAB_AUTH_TOKEN: ${{ secrets.GITCONTRIB_GITLAB_AUTH_TOKEN }}
      run: |
        python gitContrib/main.py # path to the Python script
